# Generated by Django 5.2 on 2025-05-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('capa', models.TextField(default='')),
            ],
        ),
    ]
